spring.application.name=fen

fen.security.jwt.secret=${FEN_JWT_SECRET}
fen.security.jwt.expiration=8h
fen.security.cors.allowed-origins=${FEN_CORS_ALLOWED_ORIGINS:http://localhost:4200}

# ============================
# POSTGRESQL DATABASE CONFIG
# ============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fendb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================
# JPA / HIBERNATE CONFIG
# ============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# TODO: Mudar para 'validate' quando usar Liquibase
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# Desabilita o auto-gerenciamento do Hibernate (Liquibase vai gerenciar)
spring.jpa.open-in-view=false

# ============================
# LIQUIBASE CONFIGURATION
# ============================
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.default-schema=public
spring.liquibase.contexts=production
spring.jpa.properties.org.hibernate.envers.default_schema=aud
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_aud
# ============================
# SERVER CONFIG
# ============================
server.port=8080

# ============================
# LOGGING
# ============================
logging.level.org.springframework.security=INFO
logging.level.liquibase=INFO
logging.level.liquibase.changelog=INFO
logging.level.liquibase.executor=OFF
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.orm.jdbc.extract=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=OFF
